# NumPy

In [1]:
# using numpy
import numpy as np

In [2]:
'''
 - np.array --> faster than list
 - list --> have object datatype
 - array --> efficient memory , very fast --> store homogenous datatype
 - array --> list of all elemnet of same datatype
'''

'\n - np.array --> faster than list\n - list --> have object datatype\n - array --> efficient memory , very fast --> store homogenous datatype\n - array --> list of all elemnet of same datatype\n'

In [3]:
'''
 - defining np array
 - name = np.array([]) or np.array(())
 
 - we can specify the datatype by attribute (dtype = "type , i ,f , s") 
'''

'\n - defining np array\n - name = np.array([]) or np.array(())\n \n - we can specify the datatype by attribute (dtype = "type , i ,f , s") \n'

In [4]:
a = np.array([1,2,3,4,5])
print(type(a))

<class 'numpy.ndarray'>


In [5]:
b = np.array((1,2,3,3,4,5))
type(b)

numpy.ndarray

In [6]:
c = np.array(("mostafa","samir"))
d = np.array((12,1.5,5.7),dtype= 'i')

In [7]:
d

array([12,  1,  5], dtype=int32)

In [8]:
# showing the datatype of a np array
# using .dtype attribute

d.dtype

dtype('int32')

In [9]:
'''
 - note
 - numpy can know the datatype of a variable by its own (dnamic typing)
'''

'\n - note\n - numpy can know the datatype of a variable by its own (dnamic typing)\n'

### properities of array

In [10]:
'''
 - all datatypes of array have the same time
 - ndarray: no.dimensional array
 - shape : number of rows and columns in the array
'''

'\n - all datatypes of array have the same time\n - ndarray: no.dimensional array\n - shape : number of rows and columns in the array\n'

In [20]:
# homogenous datatype

a = np.array((1,"mostafa")) # different datatype

In [21]:
a.dtype

dtype('<U21')

In [12]:
# ndarray

c= np.array(([1,2,3],[4,5,6]))
c.ndim

2

In [13]:
# shape

c.shape # rows and columns

(2, 3)

In [14]:
# accessing elements

c[0,1]

2

### some functions in numpy

In [ ]:
'''
 - np.arange(num) --> creating an array from start num to end num
 - np.random.permutation --> creating array in range but with shuffled order
 - np.reshape -->  
'''

In [22]:
# arange

x = np.arange(1,100,2)
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [24]:
# we can make it with list and range

print(list(range(1,100,2)))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [25]:
len(x) == len(list(range(1,100,2)))

True

In [28]:
# permutation

A = np.random.permutation(range(10)) # array 

In [29]:
A

array([3, 7, 8, 5, 1, 0, 9, 4, 2, 6])

### Random module

In [30]:
np.random.randint(0,50) # creating random integer

33

In [31]:
# creating array of random elements from 0 to 1

A = np.random.rand(1000) # uniform distribution

In [33]:
A.shape

(1000,)

In [34]:
A = np.random.randn(1000) # guassian distribution

In [35]:
A

array([ 2.59994795e-01,  4.55856945e-01,  1.64936812e+00, -8.78841376e-01,
       -5.19469590e-01, -5.21361179e-01,  1.36258595e+00,  1.14074996e+00,
        6.34953260e-02,  2.76551305e-01, -1.53823336e-01,  9.01744094e-01,
        8.41774696e-01, -2.89031536e-01, -8.61873868e-02,  1.67185956e+00,
       -1.04990079e-01,  2.50673307e-01, -3.77668814e-01, -3.58028856e-01,
       -6.66801522e-01,  9.81595354e-01, -5.22088818e-01, -1.53028195e+00,
        2.43873514e-01,  1.38156981e-01,  2.49649455e-01,  7.86201792e-01,
        2.65380560e-01, -1.08691990e+00, -3.06248377e-01, -2.26654767e-01,
        7.07597177e-01,  1.63018626e+00, -4.43923874e-01,  1.78860980e+00,
        1.53300557e-01, -9.31664859e-01, -1.21095130e+00, -1.13585491e+00,
       -5.98663311e-01,  2.39014341e-01,  5.19195265e-03,  1.06660892e-01,
       -1.94460189e-01, -2.86686075e-02,  2.10557199e-01,  8.38230406e-01,
        6.61266974e-01, -1.34125749e-01,  3.88116854e-01,  1.15729059e+00,
        6.56331515e-01, -

In [36]:
# creating 2D array if random values

C = np.random.rand(2,3)

In [38]:
C.ndim

2

In [39]:
# reshape --> changing the shape of an array 
# useful in creating a matrix

A = np.random.rand(100).reshape(4,25)

In [40]:
A

array([[0.91518333, 0.95927375, 0.65604529, 0.87499017, 0.68367709,
        0.99464839, 0.41449853, 0.72014063, 0.10825095, 0.68164443,
        0.14891107, 0.66094048, 0.81595774, 0.41567727, 0.20061131,
        0.97586942, 0.08176583, 0.62296242, 0.75653163, 0.09091717,
        0.3550306 , 0.45378303, 0.58038967, 0.93678051, 0.1374511 ],
       [0.43335903, 0.70682005, 0.04671296, 0.02016702, 0.62071148,
        0.03897293, 0.25731472, 0.20207698, 0.09794547, 0.92599696,
        0.20598263, 0.34630816, 0.81598055, 0.82901899, 0.58836845,
        0.5644441 , 0.05277758, 0.05454346, 0.31431813, 0.23063671,
        0.9485836 , 0.46468492, 0.87100818, 0.63234661, 0.28172766],
       [0.12901765, 0.70468881, 0.03304687, 0.32974153, 0.10405612,
        0.76415472, 0.97649155, 0.79289273, 0.34455049, 0.31848225,
        0.58863234, 0.3347179 , 0.11487203, 0.54102778, 0.84746319,
        0.86592825, 0.78870581, 0.90032208, 0.43426013, 0.26817456,
        0.20008194, 0.92938216, 0.6192671 , 0.

### indexing and slicing in numpy

In [ ]:
'''
 - indexing and sclicing in numpy array is the same as the indexing and slicing as in other datatypes
 - BUT ==> in numpy it doesnot take a copy of the array its accessing the actual array
 
 - ex
 - b = a[1:5]
 - b --> part of array (a) , accessing the same index of the array
'''

In [41]:
A = np.arange(100)
b = A[3:10]

In [42]:
b

array([3, 4, 5, 6, 7, 8, 9])

In [43]:
b[0] = -1200

In [44]:
A

array([    0,     1,     2, -1200,     4,     5,     6,     7,     8,
           9,    10,    11,    12,    13,    14,    15,    16,    17,
          18,    19,    20,    21,    22,    23,    24,    25,    26,
          27,    28,    29,    30,    31,    32,    33,    34,    35,
          36,    37,    38,    39,    40,    41,    42,    43,    44,
          45,    46,    47,    48,    49,    50,    51,    52,    53,
          54,    55,    56,    57,    58,    59,    60,    61,    62,
          63,    64,    65,    66,    67,    68,    69,    70,    71,
          72,    73,    74,    75,    76,    77,    78,    79,    80,
          81,    82,    83,    84,    85,    86,    87,    88,    89,
          90,    91,    92,    93,    94,    95,    96,    97,    98,
          99])

In [45]:
# if want to have a copy of the datatype

b = A[1:10].copy()
b

array([    1,     2, -1200,     4,     5,     6,     7,     8,     9])

In [46]:
A[3] = 3

In [47]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [48]:
A[::5] # printing all elements step = 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [49]:
A[::-5] # steps is from the end

array([99, 94, 89, 84, 79, 74, 69, 64, 59, 54, 49, 44, 39, 34, 29, 24, 19,
       14,  9,  4])

In [50]:
A[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [53]:
A[59] = 888

In [60]:
# finding the index of an element in the array

count = 0

for i in A: 
    if i == 888:
        print(count)
    count+=1

59


In [61]:
# make it in a function

def index_array(array , element):
    count = 0
    for i in array:
        if i == element:
            print(count)
        count+=1

In [62]:
# making a random list 

test_arr = []
for i in range(100):
    test_arr.append(np.random.randint(0,100))

In [64]:
test_arr = np.array(test_arr)

In [65]:
type(test_arr)

numpy.ndarray

In [66]:
test_arr

array([89, 92, 67, 52, 72, 97, 54,  4, 77, 78, 18, 50, 67, 80, 57, 20, 11,
       30, 43,  1,  3, 42, 11, 36, 42,  0, 77, 24, 13, 48, 47,  0, 38,  3,
       33, 32, 84, 47, 20, 52, 91, 66, 99, 99, 85, 95, 63, 51, 97, 93, 93,
       29, 62, 80,  2, 47,  1,  2, 79,  1, 29, 53, 80, 88, 27, 70, 67, 51,
       27, 48, 37, 97, 91,  4, 87, 18, 18, 84, 80, 67, 39, 54, 95, 30, 81,
       45, 41, 54, 76, 94, 34, 72, 84, 52,  2, 59, 66, 84,  0, 11])

In [67]:
index_array(test_arr , 91)

40
72


In [68]:
test_arr[40]

91

In [71]:
test_arr[72]

91

In [72]:
# knowing the index
# by argwhere

idx = np.argwhere(test_arr == 0)

In [73]:
idx

array([[25],
       [31],
       [98]])

In [74]:
test_arr[25]

0

In [75]:
test_arr[31]

0

In [76]:
test_arr[98]

0

In [1]:
import numpy as np

# FreeCodeCamp

In [1]:
# importing numpy to use it in code

import numpy as np

In [2]:
# intialaliza an array

a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# intializing 2D array

b = np.array([[1,2,2,3] , [4,5,6,7]])
b.ndim

2

In [5]:
b.shape

(2, 4)

In [4]:
# specify datatype in the array

c = np.array(["mostafa" , "samir"] , dtype = 'U7')

In [5]:
c.dtype

dtype('<U7')

In [6]:
# item size

c.itemsize

28

In [7]:
# total size 

c.nbytes

56

## accessing rows and columns

In [9]:
a = np.array([[1,2,3,4,5,6,7] , [8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [10]:
# getting a specific element

a[1,5] # row and column

13

In [11]:
# similar to list
# - notation

a[1,-5]

10

In [ ]:
# indexing and slicing is the same as a list

# matrix in numpy

In [12]:
# all 0 matrix

zeros = np.zeros([2,2])

In [13]:
zeros

array([[0., 0.],
       [0., 0.]])

In [16]:
# ones matrix

ones = np.ones([])
ones

array(1.)

In [18]:
# any other number

num = np.full([2,4] , 50)
num

array([[50, 50, 50, 50],
       [50, 50, 50, 50]])

In [19]:
# any other number 
any_ = np.full(a.shape , 4) 

In [20]:
any_

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [21]:
# array of random numbers

np.random.rand(4,2) # random nuber from 0 to 1 

array([[0.82969793, 0.26168076],
       [0.69751799, 0.30034345],
       [0.54695028, 0.43087603],
       [0.91397228, 0.60619795]])

In [122]:
int((np.random.rand()*1000) or (np.random.rand() * 100) or (np.random.rand() * 10))

11

In [126]:
# matrix of random elements with size

np.random.randint(0.3,15.7 , size = [3,3])

array([[ 1,  6,  8],
       [14,  4,  7],
       [ 5,  6, 10]])

In [127]:
# identity matrix

np.identity(5) # no specify for size because the identity matrix is always square 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [128]:
# repeating an array

arr = np.array([1,2,3])
r1 = np.repeat(arr , 5)
r1

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3])

In [6]:
# making a copy of an array

a = np.array([1,2,3])

b = a.copy()

b[0] = 100

print(a , "\n" , b)

[1 2 3] 
 [100   2   3]


## math

In [9]:
print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a **2)
print(np.cos(a))

[3 4 5]
[-1  0  1]
[2 4 6]
[0.5 1.  1.5]
[1 4 9]
[ 0.54030231 -0.41614684 -0.9899925 ]


## linear algebra

In [11]:
# multiplying matrix

a = np.ones([2,3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
b = np.full([3,2] , 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [16]:
c = np.matmul(a,b)
c

array([[6., 6.],
       [6., 6.]])

In [19]:
# determinent of a matrix

d = np.random.randint(0,19 , size = [4,4])

np.linalg.det(d)

2265.999999999997

## statistics 

In [20]:
# min of matrix
np.min(d)

3

In [21]:
# max 
np.max(d)

18

In [22]:
d

array([[ 3,  7, 18, 12],
       [ 6, 17,  8,  9],
       [10, 16, 10,  6],
       [ 7,  9, 14,  5]])

In [23]:
# min in axis 1

np.max(d , axis = 1) # axis = 1 ==> row

array([18, 17, 16, 14])

In [24]:
np.max(d , axis = 0) # columns

array([10, 17, 18, 12])

# Reorganizing array

In [25]:
d

array([[ 3,  7, 18, 12],
       [ 6, 17,  8,  9],
       [10, 16, 10,  6],
       [ 7,  9, 14,  5]])

In [26]:
d.shape

(4, 4)

In [27]:
e = np.random.randint(0,100 , size = [3,6])

In [28]:
e

array([[44, 30, 40, 42, 44, 50],
       [29, 81, 37, 65, 65, 16],
       [ 0, 39,  7, 33, 88, 30]])

In [32]:
# reshaping a matrix
# reshape is not the same as transpose

e = e.reshape((6,3)) 
e

array([[44, 30, 40],
       [42, 44, 50],
       [29, 81, 37],
       [65, 65, 16],
       [ 0, 39,  7],
       [33, 88, 30]])

In [35]:
# vertically stacking 
# vstack

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1 , v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [36]:
# horozintal stack

h1 = np.ones([2,4])
h2 = np.zeros([2,2])

np.hstack([h1 , h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# miscellaneous 

## load data from file

In [ ]:
'''
 - np.getformattxt("location" , delimeter = ",")
'''

In [ ]:
# changing datatype
'''
 - data.astype(type)
'''

## boolean masking and advanced indexing

In [43]:
test = np.random.randint(100,size = [6,10])

In [44]:
test

array([[58, 62, 52,  9, 15, 68, 82, 69, 76, 22],
       [73, 53, 40, 48, 97, 19, 44, 25, 10, 23],
       [34, 40, 76, 72, 58, 93, 67, 35, 34, 66],
       [23, 73, 72, 69, 80, 26, 83, 35,  5, 75],
       [68, 75, 66, 55, 48, 92, 83, 14, 28, 24],
       [ 1,  5,  6, 79, 71, 26, 81, 22, 29, 54]])

In [46]:
test[test > 67]

array([68, 82, 69, 76, 73, 97, 76, 72, 93, 73, 72, 69, 80, 83, 75, 68, 75,
       92, 83, 79, 71, 81])

In [52]:
# indexing with a list in numpy
test2 = np.array([1,2,3,4,5,6,7,8,9])
test2[[0,1,2,8]]

array([1, 2, 3, 9])

In [54]:
# using indexing with axis

np.any(test > 67 , axis = 0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [55]:
np.all(test > 67 , axis = 0)

array([False, False, False, False, False, False, False, False, False,
       False])